FROM node:20-alpine 

 # 20-alpine is a lightweight version of Node.js based on Alpine Linux


     COPY package.json .
    # Copy the package.json file to the container

    COPY package-lock.json .
    # Copy the package-lock.json file to the container

    RUN npm install

    COPY . .
    # Copy the rest of the application code to the container


    CMD ["node", "server.js"]
    # Command to run the application when the container starts
